# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linklib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('skey', models.CharField(max_length=6)),
                ('link', models.TextField()),
                ('click_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'linklib',
                'ordering': ['-click_count'],
            },
        ),
    ]
